name: flutter_places
description: Flutter places fully customizable widget for autocomplete, compatible with Light and Dark mode, based on https://pub.dartlang.org/packages/google_maps_webservice
version: 1.0.0+4
homepage: https://github.com/GeekAbdelouahed/flutter_places

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_webservice: ^0.0.18
  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - packages/flutter_places/assets/google_dark.png
    - packages/flutter_places/assets/google_light.png
